import os
import re
import subprocess
from celery import Celery
from celery.signals import worker_shutdown, worker_ready

REDIS_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")

celery_app = Celery(
    "tasks",
    broker=REDIS_URL,
    backend=REDIS_URL
)

celery_app.conf.update(
    broker_connection_retry_on_startup=True,
    broker_transport_options={
        'visibility_timeout': 86400,
        'max_retries': 10,
        'interval_start': 0,
        'interval_step': 1,
        'interval_max': 5,
    },
    result_backend_transport_options={
        'retry_on_timeout': True
    }
)


def cleanup_dynamic_containers():
    """Clean like an orphan container generated by dynamic landscapes."""
    try:
        cmd = ["docker", "ps", "-a", "-q", "--filter", "label=app=bugbounty_recon_runner"]
        result = subprocess.run(cmd, capture_output=True, text=True)
        containers = result.stdout.strip().split()
        if containers:
            subprocess.run(["docker", "rm", "-f"] + containers, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception:
        pass


@worker_ready.connect
@worker_shutdown.connect
def handle_worker_lifecycle(**kwargs):
    """Cleans containers when starting and turning off the worker."""
    cleanup_dynamic_containers()


def clean_ansi(text: str) -> str:
    """Removes ANSI color coding from the container output."""
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
    return ansi_escape.sub('', text)


def detect_phase(line: str) -> str:
    """Maps container text outputs to readable phase names."""
    clean_line = clean_ansi(line).lower()

    if any(k in clean_line for k in ["subdomain", "subfinder", "assetfinder", "amass", "findomain"]):
        return "Phase 1: Subdomain Enumeration (Subfinder / Assetfinder / Amass)"

    elif any(k in clean_line for k in ["port", "naabu", "nmap", "masscan"]):
        return "Phase 2: Port and Service Scanning (Naabu / Nmap)"

    elif any(k in clean_line for k in ["web", "httpx", "probing", "httprobe"]):
        return "Phase 3: Verification of Active Web Services (HTTPX)"

    elif any(k in clean_line for k in ["endpoint", "wayback", "katana", "gau", "ffuf", "gobuster", "dirsearch"]):
        return "Phase 4: Discovery of Endpoints and Routes (Katana / GAU / FFUF)"

    elif any(k in clean_line for k in ["vuln", "nuclei", "scanner", "wpscan"]):
        return "Phase 5: Vulnerability Analysis (Nuclei)"

    return "Running recognition process..."


@celery_app.task(bind=True)
def run_recon_task(self, target: str):
    # Generate a unique name based on the Celery task ID
    task_id = self.request.id or "manual"
    container_name = f"recon_scan_{task_id}"

    self.update_state(
        state='PROGRESS',
        meta={'status': f'Starting container for {target}...', 'phase': 'Initializing', 'target': target}
    )

    host_pwd = os.getenv("HOST_PWD", os.getcwd())
    host_config_dir = os.path.join(host_pwd, "bugbounty_recon", "config")
    host_output_dir = os.path.join(host_pwd, "output")

    os.makedirs(os.path.join(os.path.dirname(__file__), "output"), exist_ok=True)

    # We add -i and PYTHONUNBUFFERED=1 for bufferless streaming
    cmd = [
        "docker", "run", "--rm", "-i",
        "-e", "PYTHONUNBUFFERED=1",
        "--name", container_name,
        "--label", "app=bugbounty_recon_runner",
        "-v", f"{host_config_dir}:/data/config",
        "-v", f"{host_output_dir}:/data/output",
        "bugbounty_recon:latest",
        "--config", "/data/config/bugbounty_config.json",
        target
    ]

    logs_history = []
    current_phase = "Initializing scanner..."
    process = None

    try:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )

        for line in iter(process.stdout.readline, ''):
            if not line:
                break
            
            clean_line = clean_ansi(line.strip())
            if clean_line:
                logs_history.append(clean_line)
                if len(logs_history) > 100:
                    logs_history.pop(0)

                detected = detect_phase(clean_line)
                if detected != "Running recognition process...":
                    current_phase = detected

                self.update_state(
                    state='PROGRESS',
                    meta={
                        'status': clean_line,
                        'phase': current_phase,
                        'logs': "\n".join(logs_history),
                        'target': target
                    }
                )

        process.wait()

        if process.returncode != 0:
            raise subprocess.CalledProcessError(process.returncode, cmd)

        return {
            'status': 'SUCCESS',
            'target': target,
            'output_folder': os.path.join("/app/output", target),
            'logs': "\n".join(logs_history)
        }

    except subprocess.CalledProcessError as e:
        error_msg = f"The container ended with error code {e.returncode}"
        self.update_state(
            state='FAILURE',
            meta={'status': error_msg, 'phase': 'Error', 'target': target}
        )
        raise RuntimeError(error_msg)

    except Exception as e:
        self.update_state(
            state='FAILURE',
            meta={'status': str(e), 'phase': 'Error', 'target': target}
        )
        raise RuntimeError(str(e))

    finally:
        if process and process.poll() is None:
            try:
                process.kill()
            except Exception:
                pass

        # Ensure forced removal of the dynamic container upon termination or interruption
        subprocess.run(
            ["docker", "rm", "-f", container_name],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL
        )